# Generated by Django 5.0.6 on 2024-07-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_historicaluser_photo_user_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluser',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Password'),
        ),
    ]
