# Generated by Django 5.0.6 on 2024-07-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_historicaluser_photo_remove_user_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='ImageFace'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.TextField(blank=True, null=True, verbose_name='ImageFace'),
        ),
    ]
