# Generated by Django 5.0.6 on 2024-07-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_historicaluser_image_user_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='image',
            new_name='image_face',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='image',
            new_name='image_face',
        ),
    ]
